name: 'Mkdocs Github Pages Releaser'
description: 'Host Mkdocs projects as a Github page'
author: 'Andreas Fritzler, andreas.fritzler@gma1l.com'
runs:
  using: "composite"
  steps:
    - name: Setup mkdocs
      run: pip install --no-cache-dir -r "${{ github.action_path }}/requirements.txt"
      shell: bash
    - name: Publish mkdocs
      run: ${{ github.action_path }}/action.sh
      shell: bash